### ISSUE TITLE
Support for colors

### ISSUE THREAD

**Issue by yoava333** [ivanfratric/winafl#103]
On windows 10 and upward we can optionally add ANSI colors.

![image](https://user-images.githubusercontent.com/1495026/37892473-a1b99fc8-30e0-11e8-807a-631c81b2f2a9.png)

**Comment by 0vercl0k** [comment]
Oh that's super cool - thanks guys!

Cheers

2018-03-26 7:08 GMT-07:00 ivanfratric <notifications@github.com>:
