### ISSUE TITLE
Issues with network-app fuzzing

### ISSUE THREAD

**Issue by symeonp** [ivanfratric/winafl#131]
Hey @mxmssh thanks so much for the commit I couldn't resist not to try this feature!
Unfortunately, am having some issues with the network fuzzing.
Here's the output after literally 4mins of fuzzing:

```
[-] PROGRAM ABORT : connect() failed with error code : 10055
         Location : send_data_tcp(), c:\projects\winafl\afl-fuzz.c:2534
```
And on the server:
```Recv failed with error: 10053```

Am playing with some toy binaries just to get familiar, any ideas what may causing this?

Thanks,
Symeon

**Comment by mxmssh** [comment]
Hi Symeon, sorry for the long response (DEF CON). Could you clarify please this "Here's the output after literally 4mins of fuzzing". Does it mean that winAFL worked for the first 4 mins? What about stability (low/high)?

**Comment by mxmssh** [comment]
Ok, I got it :) It is simple:
PROGRAM ABORT : connect() failed with error code : 10055

"Error 10055 means that Windows has run out of TCP/IP socket buffers because too many connections are open at once."

So, it looks like your program is not closing connection with the server.

**Comment by symeonp** [comment]
Hey Maksim,

That's very interesting! However, it looks like the the connection gets closed, it's vulnserver which I'm planning to do a blog post once I figure it out :)

![vulnnserver_fuzzing](https://user-images.githubusercontent.com/954127/44123067-730e707e-a01e-11e8-9428-ef83130cd6aa.png)

Thanks!

**Comment by mxmssh** [comment]
Hm, could you post vulnserver's code and command line you run winAFL? It looks like something wrong with instrumentation...

**Comment by symeonp** [comment]
Yeap, it's Lupin's code: http://www.thegreycorner.com/2010/12/introducing-vulnserver.html from 8 years ago! The command line I've used is the following:
```afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_offset 0x12D0 -coverage_module vulnserver.exe -fuzz_iterations 50000 -nargs 1 -- C:\Users\ida\Desktop\vulnserver\vulnserver.exe```

That offset is pretty much main's function:
![vulnserver_main](https://user-images.githubusercontent.com/954127/44123448-49d6bde0-a020-11e8-83f2-298f71744c8d.png)

Cheers and thanks!

**Comment by mxmssh** [comment]
Ok, it looks like I start understanding the root of the problem. Basically, we have three things here:

1. You need to specify your argument for vulnserver when you are starting winAFL. For example
```afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_offset 0x12D0 -coverage_module vulnserver.exe -fuzz_iterations 50000 -nargs 1 -- C:\Users\ida\Desktop\vulnserver\vulnserver.exe 9999```

2. You don't need to run vulnserver from a separate console, winAFL will run everything for you (that's why stability is 0 here).

3. If you want to use persistent mode (argument ```-fuzz_iterations 50000```), the function __main is not a good choice :). Try to run it without persistency (just specify -fuzz_iterations 1) first and check whether it works or not. If it works (performance should be super slow), we need to modify source code to be able to enable persistent mode.

**Comment by symeonp** [comment]
Brilliant, will try that tomorrow cause it's 00:30 here, and get back to you!
Thanks, (btw vulnserver runs by default on 9999 unless you specify another port!)

**Comment by mxmssh** [comment]
Actually, you don't need to modify source code, try to run it as is. -nargs should be 2. So the resulting command is: 

```afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_offset 0x12D0 -coverage_module vulnserver.exe -fuzz_iterations 50000 -nargs 2 -- C:\Users\ida\Desktop\vulnserver\vulnserver.exe 9999```

**Comment by symeonp** [comment]
Yeah sure, although from IDA it looks like we are passing three arguments.
Generally from my experience with the exception of a few custom functions I didn't have luck instrumenting them, winafl would fail. I will test it again thoroughly and post back with a more detailed description ok? 
Many thanks!

**Comment by mxmssh** [comment]
Sounds good. Yes it looks like we need to set -nargs 3.

**Comment by mxmssh** [comment]
Ok, now the fuzzer stats looks much healthy :) Could you try to disable persistent mode (```-fuzz_iterations 1)?

**Comment by mxmssh** [comment]
It would be easier to debug if you can redirect those printf into file. We could better understand what's going on in the server.

**Comment by symeonp** [comment]
Alright, with persistent mode disabled am getting almost 0.25exec/s and exactly same error as before. I think your idea of redirecting those printfs to a file is brilliant, will do that once I get some time!
Thanks so much Maksim!

**Comment by symeonp** [comment]
Hey Maksim!

I've finally had the chance to modify the printfs to fprintf (had to use a x32 bit version of cygwin!),
am attaching the log file. It looks decent frankly as in:
```
Received a client connection from 127.0.0.1:61180
Connection closing...
Received a client connection from 127.0.0.1:61181
Connection closing...
Received a client connection from 127.0.0.1:61182
Connection closing...
```
I think it would be a good idea to add those fprintfs, to the TRUN method that I am fuzzing cause this one does not help us much..

[Here's](https://drive.google.com/open?id=1pqvylKJPjhQSRtiukACpxH8_UaL21TRR) the link for the file (sorry github is failing!)

Once again thanks!

**Comment by mxmssh** [comment]
Hi,

Did you change all printfs to fprintfs? It is pretty strange. I gonna try it tonight.

**Comment by symeonp** [comment]
Hi Maksim,

Update my side: Indeed the connections were not closed properly (took me some time to figure this out!). Here's the latest error after 9min fuzzing:

```
[-] PROGRAM ABORT : connect() failed with error code : 10055
Location : send_data_tcp(), c:\users\ida\desktop\winafl\afl-fuzz.c:2553
```

After a bit for researching it turns out:
```
WSAENOBUFS | 10055 
No buffer space available.An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
````
and then following this article [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc739819(v=ws.10)), I've modified the ```MaxUserPort``` parameter and increased it to 0xFFFE, however winafl still complains. Have you ever this seen?
Thanks!

**Comment by mxmssh** [comment]
Hi, I have tried your client and had the same issue as you had before, error code: 10061. It was happened because there is some problem with instrumenting _main routine using DynamoRIO (may be my version is out of date or something else). Which version of DR are you using ? Anyway, I see several other problems with this vulnserver:
1) vulnserver assumes that after you send your input you should receive output from them, however, winAFL doesn't support that (I have created a new pull request where it is possible to define a custom logic via third-party DLL). So, you either need to comment out all ```send``` in the vulnserver or pull new winAFL functionality and implement a custom client/server logic)
2) Infinite loop, as it is described in the winAFL README file, target should exit/close connection after processing test case. In vulnserver, they use infinite loop to receive new incoming connections and create a new thread for each one. That's why you are experiencing this problem with ```no buffer space available```. You have to remove infinite loop as well.
I have modifed the vulnserver and managed to make fuzzer work for me. You can find source code file in the attachment. 
[vulnserver.zip](https://github.com/ivanfratric/winafl/files/2346619/vulnserver.zip)

**Comment by mxmssh** [comment]
Hm, it looks like there is some problem with instrumentation (target exiting/crashing) even before executing target function. Does it work without winAFL at all?

**Comment by symeonp** [comment]
Yes Maksim, it does work, in fact I was able to crash it by sending a large string...
I guess I need to hook up a debugger and understand how this instrumentation works/why am getting this error.

**Comment by mxmssh** [comment]
Could you copy/paste here cmd you are using to execute winAFL ?

**Comment by symeonp** [comment]
Debug version:
```
afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_offset 0x17E0 -coverage_module vulnserver.exe -fuzz_iterations 500 -nargs 1 -- C:\Users\ida\Desktop\vulnserver-winafl\Debug\vulnserver.exe
```
and release:
```
afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_offset 0x1320 -coverage_module vulnserver.exe -fuzz_iterations 500 -nargs 1 -- C:\Users\ida\Desktop\vulnserver-winafl\Release\vulnserver.exe
```
results in:
```
[+] You have 2 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...

[-] The program took more than 20000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 20000+').

[-] PROGRAM ABORT : Test case 'id_000000' results in a timeout
         Location : perform_dry_run(), c:\users\ida\desktop\winafl\afl-fuzz.c:2991

process 8104 is not running under DR
0 processes nudged
```

**Comment by mxmssh** [comment]
Is this offset point to the main function ? If it is, could you try ```-fuzz_iteration=1``` and some other function (I tried ```ConnectionHandler``` and it worked for me).

BTW, if you compile your target with debug information you can use ```-target_method ConnectionHandler``` instead of offset.

**Comment by symeonp** [comment]
Ah interesting, I thought I need to export the symbol (am aware of the -target_method which didn't try at all), but reading at [this](https://github.com/ivanfratric/winafl/blob/d143d277e5c866174fa30ca8925058fc2a07e5fb/winafl.c#L656) code, it looks like winafl first tries the exported symbols and then the debug symbols as well!
Yeah, my function is indeed the ConnectionHandler... 

The -target_method gives me the ```Can't find specific method in fuzz_module``` but I'll try to export it and give it another try

**Comment by symeonp** [comment]
It worked for just 1min with crazy slow speed (back at 0.75 again!) and gave me back the old 10061 error.
The exported file was this one:
```
Dump of file C:\Users\ida\Desktop\vulnserver-winafl\Debug\vulnserver.exe

File Type: EXECUTABLE IMAGE

  Section contains the following exports for vulnserver.exe

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 00011366 _ConnectionHandler@4 = @ILT+865(_ConnectionHandler@4)
```
and the command:
```afl-fuzz.exe -p 9999 -a 127.0.0.1 -w 1000 -i in -o out2 -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_method _ConnectionHandler@4 -coverage_module vulnserver.exe -fuzz_iterations 1 -nargs 1 -- C:\Users\ida\Desktop\vulnserver-winafl\Debug\vulnserver.exe```

**Comment by mxmssh** [comment]
Well, It is very strange, the last guess I can make that I've used a new patch for winAFL. You can try to use this branch https://github.com/ivanfratric/winafl/pull/134 while we are merging it with master.

**Comment by symeonp** [comment]
So I've tried your latest pull request and still not getting lucky.
I've used the following command:
```set AFL_CUSTOM_DLL_ARGS=-p 6666 -a 127.0.0.1 -w 1000```

and fuzzed it with:
```afl-fuzz.exe -s -i in -o out -D C:\DRIO7\bin32 -t 20000 -- -target_module vulnserver.exe -target_method ConnectionHandler -coverage_module vulnserver.exe -fuzz_iterations 500 -nargs 1 -- C:\Users\ida\Desktop\vulnserver-winafl\Debug\vulnserver.exe 6666```

I haven't exhausted all the posibilities yet, I have to read a bit about your DLL harness and try that as well! Am closing the issue and maybe re-comment if I get it to work. Thanks so much!

**Comment by MostafaSoliman** [comment]
Hi @symeonp , Hope you are doing fine, I came across the 10055 error and I solved it so wanna share what I have done.
my problem was cased by 2 issues one in the server I was fuzzing and the other was in the `send_tcp_data` in the fuzzer.
the server was setting the below socket option
```
setsockopt(s, SOL_SOCKET, SO_REUSEADDR, (char*)&opt, sizeof(int));
```
When winafl restart the server, all unfinished connections were turned to `WAIT_TIME` state waiting for the final `ACK` which will never come, this leads to a huge number of `WAIT_TIME` connections that consume the system buffer. and at some point, winafl will fail to create a new socket to send the mutant data.
To solve this we need to set the `SO_LINGER` option, which seems to kill the `WAIT_TIME` connections when the server is closed
```
setsockopt(s, SOL_SOCKET, SO_LINGER, (char*)&opt, sizeof(int));
```
This issue solve half the problem, But I still had the 10055 error after some time, to make sure that the connections are closed I added `socketclose` call to the `send_tcp_data` after the shutdown
```
    if (shutdown(s, 0x1) == SOCKET_ERROR)
      FATAL("shutdown failed with error: %d\n", WSAGetLastError());
    if(closesocket(s)== SOCKET_ERROR)
      FATAL("closesocket failed with error1: %d\n", WSAGetLastError());
```
This solved the problem completly for me, I hope it will solve the problem for you too.

**Comment by symeonp** [comment]
Hey Mostafa, that's very interesting, thanks so much, I'll definitely give it a try!

Cheers,

**Comment by mxmssh** [comment]
Hey @MostafaSoliman, it is cool. Could you commit this change ?

**Comment by MostafaSoliman** [comment]
Hi @mxmssh I created a pull request with the change, Is this enough, Also it is better to add the note about the target server socket option in the README.md under the network fuzzing section.
