### ISSUE TITLE
The program took more than 60000 ms to process one of the initial test cases.

### ISSUE THREAD

**Issue by akirilov** [ivanfratric/winafl#17]
Getting the following error:

```
C:\Users\akirilov\Desktop\test3>afl-fuzz.exe -i "inputs_small" -o "outputs" -D "C:\DynamoRIO-Windows-6.2.0-2\bin64" -t 60000 -f (redacted) -- -coverage_module (redacted) -coverage_module (redacted) -coverage_module (redacted) -fuzz_iterations 1 -target_module (redacted) -target_offset 0x11AC -nargs 2 -- "C:\xxxx\xxxx\(redacted)" (redacted)
WinAFL 1.02 by <ifratric@google.com>
Based on AFL 1.96b by <lcamtuf@google.com>
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'inputs_small'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...

[-] The program took more than 60000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 60000+').

[-] PROGRAM ABORT : Test case 'id_000000' results in a hang
         Location : perform_dry_run(), ..\afl-fuzz.c:2511
```

My modules are just the module name (foo.dll) so not using the full path this time. I see the target program launch and exit cleanly, and it takes significantly less than a minute, yet I still get the same error message no matter how high I set the timeout. I tried without any coverage modules too in case that was the issue, and still no luck.

**Comment by akirilov** [comment]
Also tried with various fuzz-iterations values. I figured 1 would be safe since it won't expect more than 1 iteration in the timeout period.

**Comment by ivanfratric** [comment]
Besides timeout, hangs like this typically occur when the target fails to report back to afl-fuzz, which can happen if the target_offset is incorrect or the target function does not return cleanly. These issues should be caught by the debug mode though. What does your debug log look like for this particular sample?

**Comment by akirilov** [comment]
Ah, it's possible the target function isn't returning. I take it the app can't exit without the target function returning?

Where do I find the debug log?

**Comment by akirilov** [comment]
I'm seeing a possibly related issue where module names are incorrectly case-sensitive.

"FOO.DLL" (the way it is in the filesystem) causes the timeout error
"foo.dll" (all lower) gives me a "No instrumentation detected" error
"fookdsjfklsjdklfs.dll" (not a real module) also gives me the timeout

This leads me to think that module names are converted to all lower and made case-sensitive?

**Comment by ivanfratric** [comment]
- Your target_function needs to return normally (except in the case of crash or a hang) in order for WinAFL to be able to redirect the execution back to its beginning.

 - Please see the README for info on the debug mode. Once you run in the debug mode, the debug log should be created in the current directory.

 - Module names are indeed case sensitive and should be exactly the same as in the debug log (this may or may not correspond to the filename). This is also mentioned in the README.

**Comment by akirilov** [comment]
- Changed to a function that returns normally
- Module names changed according to the debug mode list
- Still have the issue listed above where it never finishes the dry run
- With the -debug flag, it fails saying it cannot find and kill the child process (I assume this is normal)

Log file contents (filenames removed and long sequences of module loads truncated):
```
Module loaded,
...
Module loaded,
In OpenFileW,
Module loaded,
...
Module loaded,
In OpenFileW, reading C:\Windows\Microsoft.NET\Framework64\\v2.0.50727\clr.dll
In OpenFileW, reading C:\Windows\Microsoft.NET\Framework64\\v2.0.50727\mscorwks.dll
In OpenFileW, reading C:\Windows\Microsoft.NET\Framework64\\v4.0.30319\clr.dll
In OpenFileW, reading C:\(redacted)\(redacted)\(THE APP).exe.config
Module loaded,
...
Module loaded,
In OpenFileW, reading
Module loaded,
...
Module loaded,
In OpenFileW, reading
Module loaded,
...
Module loaded,
In OpenFileW,
Module loaded,
In OpenFileW,
In OpenFileW,
In OpenFileW,
In OpenFileW,
Module loaded,
In OpenFileW,
Module loaded,
Module loaded,
Module loaded,
In pre_fuzz_handler
In OpenFileW, reading (THE FUZZED FILE)
In OpenFileW, reading (THE FUZZED FILE)
In OpenFileW,
In OpenFileW,
In OpenFileW,
In OpenFileW,
Module loaded,
...
Module loaded,
In OpenFileW,
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
```

**Comment by ivanfratric** [comment]
Looking at your debug output, it seems that your (THE FUZZED FILE) is being opened *outside* the target function. This has the effect that WinAFL will not be able to replace the input file for every iteration and will need to kill the target process for every iteration in order to do it. That's why the dry run is taking a long time and you're getting messages about nudging/terminating the child process.

**Comment by akirilov** [comment]
Not sure I understand. It seems to be opening inside the target function, at least the first time:

```
In pre_fuzz_handler
In OpenFileW, reading (THE FUZZED FILE)
In OpenFileW, reading (THE FUZZED FILE)
In OpenFileW,
In OpenFileW,
In OpenFileW,
In OpenFileW,
Module loaded,
...
Module loaded,
In OpenFileW,
In post_fuzz_handler
```

**Comment by mrpeppels** [comment]
Above behaviour is consistent with selecting a function that does contain the file access, but is too high up in the execution. By that i mean that the function does return, but only after running the appropriate function down the line. The sequence of In pre-and post-fuzz messages without file open seem like the target function only opens the file once. Hence i suspect your target function is too "broad".
I'm curious what info ivan can provide.

**Comment by akirilov** [comment]
I can definitely believe "too broad". I chose a function very high up to ensure that the file open is contained (and I just moved it even higher up with the same result).

I'm not sure if it's possible to scope it down any further. The file open happens very early into the parsing. Any clue why "too broad" is an issue with AFL?

**Comment by mrpeppels** [comment]
This is dependent on the execution flow of the program. I suggest using IDA to get a visual impression of how it runs. My feeling is the function you selected only eventually opens the file if given certain parameters or in a certain state of the program; it's behaviour under DynamoRIO seems to be very variable in your case. 

To find a suitable function, i tend to open the file while running ProcMon, then filter for file access. Then right-click the desired file access and view the associated stack trace. Again, i'd love to get some feedback from the developer on an optimal strategy to select an appropriate function.

**Comment by akirilov** [comment]
Ah, interesting. I was just following up with procmon as well to confirm. I understand the scenario you're talking about but I'd be somewhat surprised if that's the way the execution is working. The broadest function I used is before argument parsing, so as far as I can tell it would *have* to open the file each time (clearly that's not happening).

I wonder if it's some interaction between the program, DynamoRIO, and/or AFL. How does DynamoRIO interact with Control Flow Guard? It shouldn't matter since control flow is redirected to a valid function, but maybe I'm missing something?

Also, am I correct in understanding that AFL basically jumps back to the target function after it's done running every time for (# OF ITERATIONS) times? In which case, I wonder if some global state might be causing issues.

**Comment by mrpeppels** [comment]
This is where my expertise ends as far as i can tell :). But one thing i would like to mention is the bit abour argument parsing; by parameters i don't mean the options passed to STDIN but rather the internal functions of the executable. The functions these get passed to are only visible with symbols.
https://msdn.microsoft.com/en-us/library/windows/hardware/ff552052(v=vs.85).aspx

**Comment by akirilov** [comment]
Yeah, I got what you meant :)

I specifically picked the function that parses the command line arguments since that seems to be the least likely to maintain some kind of weird global state (and should definitely enclose the file open, since the filename is specified in the command line).

And I do have full symbols and source for my target, thought that hasn't helped much with debugging AFL/DynamoRIO

**Comment by ivanfratric** [comment]
Ah sorry, I didn't see that the file was open inside the target function the first time.

Another thing that could cause this behavior (besides the global state as mentioned previously) is incorrect restoring of the target function parameters (in which case it's possible the target function errors out before it can open the file). Take a look if nargs param is correct.

In general, I can't provide much guidance for selecting the target function apart from what was already said. Unless a target is a simple command line utility that exits after processing the input (like a typical target for linux AFL would be) where just using main or a similar function will do, it will take some reversing to find a good offset.

**Comment by akirilov** [comment]
Ooooh.... -nargs specifies the number of arguments to the function, not the command line! That certainly explains a lot.

However, I would expect -fuzz_iterations 1 to still work correctly even with the wrong -nargs parameter. How many iterations does the dry run do? Am I just not waiting long enough for it to finish?

**Comment by mrpeppels** [comment]
Yes :). I already suspected there was a misunderstanding there. STDIN (standard input) in cmd is the keyboard input so maybe that was a bit unclear.

You indicate that an iteration takes ~0.5 minutes, this means there is still something going wrong. 
This means the function you selected -is- returning, but only after doing a ton of work. 
Your input files should be as small as possible, optimally <1kb. The purpose of selecting a target function is to speed up the process, which is very important in fuzzing. So the function you target should be as narrow and self-contained as possible.
I can imaging a lot is happening in the time your test case takes; this makes the fuzzing effort quite unmanageable because the behaviour is so unpredictable.

**Comment by mrpeppels** [comment]
As for the question of the iterations on the dry run, afl-fuzz.c:2440 has this comment:

/* Perform dry run of all test cases to confirm that the app is working as
   expected. This is done only for the initial inputs, and only once. */

**Comment by akirilov** [comment]
Unfortunately, there isn't much to be done to speed up the run. 30 seconds is longer than average for the app (I assume DynamoRIO instrumentation is slowing it down a lot), but this is a very large program with extremely complicated parsing code. Is there any way to get WinAFL working with long parse times like that?

**Comment by mrpeppels** [comment]
No. The function you selected is so high-up that it seems to present two fundamental problems:
1) The code is so complex that not every fuzz iteration behaves the same, leading to the function not restoring or false positives in instrumentation. 
2) The chance of finding bugs is greatly decreased at slow speeds,  AFL needs a lot of iterations to 'learn'.
The more complex the code, the more iterations it needs. 

You still needs days if not weeks to get good coverage on a medium sized media DLL at 100 execs / s. So you need to find a balance between how much code you want to cover and the speed, this will increase your chance of success literally thousandfold. Trying to get low speeds to work kind of misses the point in my view.

I think we might be able to help you better if you provide some info of your target and the size of your input files. I highly doubt a large part of those 30 seconds of work is useful to the fuzzing process.

**Comment by ivanfratric** [comment]
@akirilov Normally setting fuzz_iterations to something larger than 1 is how you'd get the largest speedup. WinAFL would be at its slowest the first time it passes through the code, because at that time the code needs to be translated. Afterwards, it is cached so subsequent runs (especially those that do not encounter new coverage) should not exceed 2x native speed. I'm not sure if with correct nargs you can increase fuzz_iterations or is there still a problem.

However if it takes seconds to process the input file natively, I agree with @mrpeppels that it might take a very long time for AFL to get good coverage. In fact it will take a very long time to finish even a single pass over a single file. One thing you can do is to use the -S id option to have WinAFL run in a non-deterministic mode and tamper with the code to reduce the iteration count per sample. This won't make a single iteration run faster but might discover new coverage more quickly (at the expense of thoroughness) for slower targets.

**Comment by akirilov** [comment]
I think I was unclear when I was talking about opening times. It takes <1s normally and about 15 seconds under WinAFL. I suspect something else may be going on that's slowing it down.

I did try increasing fuzz_iterations using several different functions up and down the callstack, but even with the correct number of args, the process had to be killed every time. I suspect the program has so much stored global state that restoring the function is incredibly difficult.

I couldn't find this anywhere, but what are the rules for coverage modules? I noticed that if I have too few it says there's no instrumentation. I'm wondering if I have the right amount now or if I have too many (or if some of them are too big). Is there a way to know which ones or how many AFL expects? Or a good rule of thumb?

**Comment by ivanfratric** [comment]
The "no instrumentation" message means that no code in the modules you specified was ever ran. You can probably discard those modules as they are not relevant for parsing input files. The good rule is to only use modules that do input file parsing and no other modules (every additional module is going to introduce a slowdown and possibly flaky coverage you don't care about).

**Comment by akirilov** [comment]
Ah, I see. I removed a bunch of coverage modules and it seems to be a little faster now. Letting it run to completion goes into the main fuzzing logic so I guess I was just impatient with killing it after 5 minutes. I'll mark this as closed and maybe we can follow up offline for ideas on how to speed it up if you're ok with that.

**Comment by ivanfratric** [comment]
If I was you I'd concentrate on figuring out why multiple iterations don't work as this is the best bet to speed it up. You wrote you had the source code for a target so perhaps there is a reasonable way to patch it.

**Comment by akirilov** [comment]
Yeah, that's my big goal right now. However I'm concerned that won't even help that much. Basically, the issue I'm running into is this:

- The code I'm targeting is in one massive binary
- The file open effectively happens in the main function, so I can't target a function lower down because then we would always be looking at the same file

I'm guessing there isn't an easy way to address this

**Comment by mrpeppels** [comment]
The executable always loads the same filename, the contents of the file is what changes during iterations.
FYI, the parameters of the function don't change during runs, AFL just needs the -nargs to restore the state if i'm not mistaken.

**Comment by ivanfratric** [comment]
If the file open happens in main, then you should use main as the target function, otherwise (in general, might vary depending on how the file is actually open) WinAFL might not be able to replace a file that is at the same time open by the target. But the main problem I see is that the file isn't being opened on subsequent iterations of main as seen in the debug log you posted earlier - I'd concentrate on fixing that.

**Comment by akirilov** [comment]
What calling conventions are you using for saving the arguments? I can't find where it's specified in the source. I'm guessing x64 uses DRWRAP_CALLCONV_MICROSOFT_X64?

**Comment by ivanfratric** [comment]
I'm not explicitly specifying a calling convention and assuming drwrap selects the correct default for the platfrom (see DRWRAP_CALLCONV_DEFAULT in https://github.com/DynamoRIO/dynamorio/blob/a71bf92fb995dada7bfb93046655b6f7c94a22e0/ext/drwrap/drwrap.h#L381)
