### ISSUE TITLE
Program output gets mixed with afl status view

### ISSUE THREAD

**Issue by mrpeppels** [ivanfratric/winafl#21]
When fuzzing a few extraction binaries i bumped into an inconvenience;

Having the program extract the input to stdout is neccesary to avoid tons of 'unique' extracted files with mangled filenames. And also because i find it soothing to watch a bunch of illegal unicode flash by XD.
 But when i do this the output gets mixed with afl's.
i've tried redirecting the output to NUL and starting it in another window, unfortunately this doesn't play nice with how the command is passed to winafl.

Would it be possible to have the target binary start from a new window? Or could i do this myself and am i overlooking a command?

**Comment by mrpeppels** [comment]
for anyone interested:

afl-fuzz.exe -t 1000+ -i - -o ../../fuzz/unrar/o -D C:\Tools\DR\bin32  -- -fuzz_iterations 5000 -target_module unrar.exe -nargs 1 -target_offset 0x170d0 -coverage_module unrar.exe  -- C:\Tools\fuzz\unrar\unrar.exe p @@

[unrar.zip](https://github.com/ivanfratric/winafl/files/529164/unrar.zip)

**Comment by mrpeppels** [comment]
Misclicked the close, apologies for the reopen.

for anyone interested:

afl-fuzz.exe -t 1000+ -i - -o ../../fuzz/unrar/o -D C:\Tools\DR\bin32  -- -fuzz_iterations 5000 -target_module unrar.exe -nargs 1 -target_offset 0x170d0 -coverage_module unrar.exe  -- C:\Tools\fuzz\unrar\unrar.exe p @@

[unrar.zip](https://github.com/ivanfratric/winafl/files/529184/unrar.zip)

**Comment by ivanfratric** [comment]
There isn't currently a command to do this but if you want to change this behavior it should be doable by passing different flags to CreateProcess() in https://github.com/ivanfratric/winafl/blob/master/afl-fuzz.c#L2040

**Comment by 0vercl0k** [comment]
@mrpeppels have a look at https://github.com/ivanfratric/winafl/commit/f51465321c5e6f826bea26253672070aa211cc4d :).

Cheers

**Comment by ivanfratric** [comment]
I believe @0vercl0k 's patch fixes the issue.
