### ISSUE TITLE
DynamoRIO doesn't work with winafl.dll

### ISSUE THREAD

**Issue by nevermoe** [ivanfratric/winafl#25]
Hi, I ran the command like the following to check if DynamoRIO works with winafl:

```
D:\fuzz\DynamoRIO-Windows-6.2.0-2\bin32\drrun.exe -c D:\fuzz\winafl\bin32\winafl.dll -debug -target_module VUPlyaer.exe -target_offset 0x4532a0 -fuzz_iterations 10  --  VUPlayer.exe in
```

However, this command will terminate within 1 second and output nothing, no error, no logs. If I remove the `-c winafl.dll` option, the dynamo will somehow open the targeted exe file for me. It seems winafl has some problem working with dynamo. 

Besides, if I use the following command, winafl seems to enter a endless loop and not taking CPU usage at all. The target program's process is also not showing up in the task manager.

```
D:/fuzz/winafl/bin32/afl-fuzz.exe -i in -o out -D D:/fuzz/DynamoRIO-Windows-6.2.0-2/bin32 -t 20000 --  -fuzz_iterations 5 -target_module VUPlayer.exe -target_offset 0x4532a0 -nargs 2 -- VUPlayer.exe
```

BTW, I'm using DynamoRIO 6.2.0-2.

**Comment by ivanfratric** [comment]
test_gdiplus.exe is not meant to output anything to console. However, you should find a log file in your current directory.

**Comment by nevermoe** [comment]
Sorry, my bad. I changed my description. I was using another program in my command. Would you please review my command again?

**Comment by ivanfratric** [comment]
Does it work correctly if you run DynamoRIO without any client? E.g.
D:\fuzz\DynamoRIO-Windows-6.2.0-2\bin32\drrun.exe --  VUPlayer.exe in

**Comment by nevermoe** [comment]
Yes, If use the command just as you typed, the VUPlayer.exe will open a UI window normally.

And I just test the test command in README file, it neither output any logs.

**Comment by ivanfratric** [comment]
Not sure what the reason for this behavior would be and it's very difficult to tell without log or other kind of data. However I encountered similar issues when testing with Microsoft EMET enabled. If you have MS EMET or an antivirus running (which might prevent injecting code into the target app) could you disable it and try again.

**Comment by nevermoe** [comment]
Yes, it's the issue! I tried again on a VM without any anti-virus soft and it works. Thank you very much! May be you can add some warning information to your next release under this situation.
