### ISSUE TITLE
Speeding Up Dry Runs?

### ISSUE THREAD

**Issue by akirilov** [ivanfratric/winafl#27]
So I've made some drastic changes to the program I was struggling with before and I've gotten runs down to a fraction of a second. However, now I'm having issues with my dry runs since I have a huge folder of templates.

Is there any way to shorten the dry run? And is there any way to reuse dry run results over the same templates in future runs? (For instance, to speed up a distributed fuzzing system)?

**Comment by ivanfratric** [comment]
You can change the number of iterations performed during the dry run in config.h, see https://github.com/ivanfratric/winafl/blob/master/config.h#L69
