### ISSUE TITLE
The program took more than 2000 ms to process one of the initial test cases

### ISSUE THREAD

**Issue by the-st0rm** [ivanfratric/winafl#3]
I am trying to fuzz with aflwin .. I have created a very simple print hello world application

```
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv)
{	
        printf("argv[1]: %s\n", argv[1]);
	printf("Hello world\n");
	return 0;
}

```

Then I tried to fuzz using the following command 

```
afl-fuzz.exe -i test_dll\in -o test_dll\out -D \path\to\DynamoRIO-Windows-6.1.1-3\bin64 -t 2000 -- -targert_module simple.exe targer_offset 0x1720 -fuzz_iterations 100 -- simple.exe @@
0 processes nudged
afl-fuzz 1.96b by <lcamtuf@google.com>
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'test_dll\in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
Attempting to load .DLL: test_dll2...
DLL handle is: 6a1c0000
file: test_dll\out\.cur_input
arg1: test

[-] The program took more than 2000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 2000+').

[-] PROGRAM ABORT : Test case 'id_000000' results in a hang
         Location : perform_dry_run(), ..\afl-fuzz.c:2451
```

I tried to locate what is wrong .. the only thing I can see when I try to run 

`C:\>path\to\DynamoRIO-Windows-6.1.1-3\bin32\drrun.exe -c winafl.dll -debug -target_module abc\simple.exe -target_offset 0x016F4 -fuzz_iterations 10 -nargs 2 -- abc\simple.exe`

It doesn't run the application 10 times ... it only run the application once !! 
Any ideas? ?

**Comment by eltuerto** [comment]
there are a couple typos in there, could that be it? You should see an invalid option message though, so I don't think so
`-targert_module simple.exe targer_offset 0x1720`

I saw something like that when I made a mistake in the target_offset, also not getting all 10 prints when running drrun. After I fixed it, it ran fine. I am passing the offset to `main `in the test.exe

**Comment by the-st0rm** [comment]
> I saw something like that when I made a mistake in the target_offset, also not getting all 10 prints when running drrun. After I fixed it, it ran fine. I am passing the offset to mainin the test.exe

This is exactly what I am getting. Apart from from the typo which isn't the reason, so how u got the main address? It should be simple.. I opened IDA pro .. checked the main address and that's it .. but still I am not able to get the 10 prints when running drrun ..

**Comment by eltuerto** [comment]
Well, you can just do x test!main and substract the base you get from lm in windbg. I use `dia2dump -sym main test.pdb` which allows me to do it in a command line but it's the same thing as doing it in windbg

**Comment by the-st0rm** [comment]
@eltuerto  I know this is should be easy, but I don't know WTH wrong I have ... so basically 
"lm command in widbg returns"

```
start             end                 module name
00000000`00400000 00000000`00422000   image00000000_00400000   (deferred)             
00000000`77860000 00000000`7797f000   kernel32   (deferred)             
00000000`77a80000 00000000`77c2a000   ntdll      (export symbols)       C:\Windows\SYSTEM32\ntdll.dll
000007fe`fda80000 000007fe`fdaea000   KERNELBASE   (deferred)             
000007fe`fde20000 000007fe`fdebf000   msvcrt     (deferred)   
``` 

The start address of the 0x400000. The main is at 0x4014F0 so the target-offset should be 0x14F0

The final command is 

`C:\>C:\path\to\DynamoRIO-Windows-6.1.1-3\bin64\drrun.exe -c winafl.dll -debug -target_module test.exe -target_offset 0x14F0 -fuzz_iterations 10 -nargs 2 -- test.exe`

It doesn't iterate and only runs the program once !! ..

I even tried to change -nargs to 3 or 1 .. same problem! this is driving me crazy

**Comment by the-st0rm** [comment]
Fuck I got why! 

This is what I was literally executing 
`C:\>C:\path\to\DynamoRIO-Windows-6.1.1-3\bin64\drrun.exe -c winafl.dll -debug -target_module test_folder\test.exe -target_offset 0x14F0 -fuzz_iterations 10 -nargs 2 -- test_folder\test.exe`

doesn't  work ....

I had to put test.exe in the parent directory ... so I execute it that way

`C:\>C:\path\to\DynamoRIO-Windows-6.1.1-3\bin64\drrun.exe -c winafl.dll -debug -target_module test.exe -target_offset 0x14F0 -fuzz_iterations 10 -nargs 2 -- test.exe`

That's really bad :-(

**Comment by ivanfratric** [comment]
FYI the target doesn't need to be in the same directory (not sure about relative paths, but absolute paths work for sure, I run it like this all the time).

However looks like the problem was in:
-target_module test_folder\test.exe
since modules in winafl are referenced by names that don't include paths.

In general, the easiest way to get the module name "right" is to look at the log file produced in the -debug mode. It lists all the modules loaded by the target (with their preferred names).

**Comment by the-st0rm** [comment]
@ivanfratric  a bit off-topic but there is there a way I can run afl-cmin on Windows?

**Comment by ivanfratric** [comment]
Only if you help to port it on windows ;-) Shouldn't be too difficult, but porting afl-fuzz was a priority :-)

**Comment by the-st0rm** [comment]
I would love to. Once I finish my master degree (in < a month) I can do
that ^^. Feel free to assign a task if u want. :)

**Comment by ivanfratric** [comment]
Good luck with your masters! We can sync afterwards if you'll still want to do this.

Also thanks a lot @eltuerto for helping out while I was away. (I just returned from vacation and also my schedule in the upcoming weeks is going to be a bit crazy).

**Comment by eltuerto** [comment]
No problem, @ivanfratric I am glad to be of help.
