### ISSUE TITLE
execution speed very slow

### ISSUE THREAD

**Issue by the-st0rm** [ivanfratric/winafl#4]
I am testing a DLL library by creating a wrapper around that DLL and basically calling functions on it. Everything looks working ok but execution speed is `0.38 exec/sec`!! that's pretty bad. Is that normal or I am missing something. I am loading the DLL dynamically using ` LoadLibrary()`, I know that slows the execution a bit but not the level of `0.38 exec/sec`

Any ideas?

**Comment by ivanfratric** [comment]
Yes that does sound pretty slow. What's the execution speed if you just run your target natively? I don't think LoadLibrary should be the bottleneck, but if it is you can only call it once at the beginning of your test program and then create another function that you'd actually fuzz (without calling LoadLibrary for every iteration).

**Comment by the-st0rm** [comment]
So basically execution without LoadLibrary() reaches up to 600 exec/sec 
When I just LoadLibrary() it drops to 13 exec/sec. You can see below my main function. A very simple Main that basically loads the DLL and free it just to benchmark

```
int main(int argc, char **argv)
{	
   char DLL[] = "ABCpdfCE5";
   HANDLE Proc;
   HINSTANCE hDLL;
   int ret;
   printf("Attempting to load .DLL...\n");
   hDLL = LoadLibrary(DLL);
   if(hDLL == NULL)
    {
      printf("DLL NAME: %s\n", DLL);
      printf(".DLL load FAILED!!1\n");
      return -1;
    }
    FreeLibrary(hDLL);//release the DLL library 
    return 0;
  
}
```

**Comment by ivanfratric** [comment]
It would be also nice to know what the execution speed is without any instrumentation, to establish what the "normal" behavior is.

However, since you are unloading the library every time, it is quite possible that dynamorio has to translate a lot of code anew for every iteration which introduces unnecessary overhead. The way to work around this is:

void fuzz() {
   //call functions on a dll
}

int main(int argc, char **argv)
{ 
   hDLL = LoadLibrary("foo");
   fuzz()
   FreeLibrary(hDLL);
}

And then use the target_offset of fuzz() instead of main().

**Comment by the-st0rm** [comment]
`It would be also nice to know what the execution speed is without any instrumentation, to establish what the "normal" behavior is.` 
That's why I tested a simple hellow_World app and got the execution speed to be around 600 exec/sec

I will try your suggested solutions, seems very tempting!

Btw, will DynamoRIO be able to instrument the code if the binary was written in .NET? a C# code basically?? (I think no!)

**Comment by the-st0rm** [comment]
`However, since you are unloading the library every time, it is quite possible that dynamorio has to translate a lot of code anew for every iteration which introduces unnecessary overhead. The way to work around this is:

void fuzz() {
//call functions on a dll
}

int main(int argc, char **argv)
{ 
hDLL = LoadLibrary("foo");
fuzz()
FreeLibrary(hDLL);
}

And then use the target_offset of fuzz() instead of main().`

That was it. This basically enhanced the fuzzing speed from 7 exec/sec to 200 exec/sec .. which isn't bad.
