### ISSUE TITLE
What's target_offset referrd to?

### ISSUE THREAD

**Issue by dwfault** [ivanfratric/winafl#47]
Hello :)
It's a question when winafl is used to fuzz about the following parameter:
-target_offset   - offset of the method to fuzz from the start of the module.

It confused me in the following situations:
1. It could refer to the offset to the module in the executive file.
2. It could refer to the offset to the module in the running process memory.
In those situations target_offset could be different. By reading the source code, I think it might be the 2nd one. But I'm not sure, is that correct?And it might be related to the implementation of DynamoRIO? 

Thanks very much!

**Comment by ivanfratric** [comment]
You are correct, it is the offset in memory (relative virtual address)
