### ISSUE TITLE
usage of target_method

### ISSUE THREAD

**Issue by abhishiktvv** [ivanfratric/winafl#48]
i have a method , which is basically a constructor. whenever i provide target_method with method name it pops error saying cant find specific module in fuzz_method.
i also have the debug symbols located in same directory of binary.
please help me out in writing proper syntax for executing code

**Comment by 0vercl0k** [comment]
If you want to use -target_method, your function must be in the export
address table of your executable; you can try to use __declspec(dllexport)
for that. Otherwise you should use -target_offset :).

Cheers

2017-03-08 8:05 GMT-08:00 abhishiktvv <notifications@github.com>:

**Comment by abhishiktvv** [comment]
Thanks @0vercl0k , actually i cannot use offset since i want to fuzz a managed code application . where we get MSIL so it's offset will be not static. could you give me any idea of fuzzing managed code applications 
Thanks in advance. :)

**Comment by 0vercl0k** [comment]
I think the best shot you have is to wrap the execution around some sort of
"main" / entry-point function (assuming a lot of other things go well too)
- did you give that a shot?

Cheers

2017-03-08 11:08 GMT-08:00 abhishiktvv <notifications@github.com>:

**Comment by ivanfratric** [comment]
Out of curiosity, what do you hope to achieve by fuzzing a managed code application? WinAFL is primarily designed to catch memory safety issues (memory access violations etc.) and those shouldn't be present in managed code (unless your intention is to fuzz the interpreter itself). If your managed code app loads a native code library and you want to fuzz that, then writing your own harness around the library might be a better approach.

**Comment by abhishiktvv** [comment]
Yes, exactly 1. I want to fuzz the native components that are being used
inside the application.
                    2.i want to check for unhandled exceptions.

**Comment by ivanfratric** [comment]
-fuzz_method is now going to look up debug symbols as well as exported symbols

**Comment by florax-k** [comment]
Is there a way to indicate where the debug symbols are located? I have the pdb file in the same directory as the exe, and I'm able to see the debug symbols in WinDbg, but when I run drrun.exe (step 2 of general steps) with the same format as the example command, it's unable to find the debug symbol (I'm using the symbol Main).

**Comment by florax-k** [comment]
The other way I tried to attach it was with target_offset instead, but the offset I calculated from the addresses in WinDbg resulted in "WARNING: Target function was never called. Incorrect target_offset?" in the log.
