### ISSUE TITLE
Enabling PageHeap while fuzzing?

### ISSUE THREAD

**Issue by rgerman** [ivanfratric/winafl#51]
Hi @ivanfratric!

I'm using WinAFL to fuzz some small apps and I was wondering if I should enable PageHeap during the fuzzing campaign. I would say *yes*, but maybe it could lead to some bugs with DynamoRIO or it slows down the executions per second. Do you have any advice?

Thanks!

**Comment by 0vercl0k** [comment]
You should absolutely enable it Germán - it's definitely a must have :).

Cheers

2017-05-11 9:15 GMT-07:00 Germán Riera <notifications@github.com>:

**Comment by rgerman** [comment]
Yeah, I thought so.

Thank you very much @0vercl0k!

I will close the issue then :)
