### ISSUE TITLE
README says "relative path" but should say "full path"

### ISSUE THREAD

**Issue by florax-k** [ivanfratric/winafl#55]
My particular folder structure had 3 layers of folders since I unzipped the DynamoRIO stuff into a folder outside of the project and it failed to find the DynamoRIO files. When I used the full path, it was able to compile.

**Comment by ivanfratric** [comment]
Note that the path should be relative to the *source* directory and not the current directory (which is usually the build directory). However you are right that the full path can be used as well and I changed the README to indicate this.

**Comment by florax-k** [comment]
Ah, I misread. Thank you!
