### ISSUE TITLE
binary file afl-fuzz.exe was out of date (slave mode not supported)

### ISSUE THREAD

**Issue by trylab** [ivanfratric/winafl#61]
The current version of afl-fuzz.exe did not support the **-S** parameter in master-slave mode. The patch can be found at https://github.com/ivanfratric/winafl/commit/d22dff76e04f6dd56f8ccfeedf9663a71d2faa40. Could you please recompile the source code and update the binary file?

**Comment by ivanfratric** [comment]
Ah yes, thanks for reminding me! Binaries should be up to date now (version 1.09b).
