### ISSUE TITLE
winafl-cmin.py issues

### ISSUE THREAD

**Issue by doria90** [ivanfratric/winafl#65]
hey all,
I'm trying to use the winafl-cmin.py file for corpus distillation but I'm having troubles running it.
Here's the command I tried and the result:

`python winafl-cmin.py -i "C:\Users\john\Desktop\results\seed_files" -o "C:\Users\john\Desktop\results\syncdir" -coverage_module shimgvw.dll -target_module PhotoViewerLoader.exe -nargs 2 -D "C:\users\john\Desktop\DynamoRIO-Windows-6.2.0-2\bin32\" -target_offset 0x1040 -t 10000 -- PhotoViewerLoader.exe @@`

`corpus minimization tool for WinAFL by <0vercl0k@tuxfamily.org>
Based on WinAFL by <ifratric@google.com>
Based on AFL by <lcamtuf@google.com>
usage: winafl-cmin.py [-h] -i dir -o dir [-n] [--working-dir dir] [-v]
                      [-covtype {edge,bb}]
                      [-call_convention {stdcall,fastcall,thiscall,ms64}]
                      -coverage_module module -target_module module -nargs
                      nargs -D dir
                      (-target_method method | -target_offset rva offset)
                      [-t msec] [-f file] [-C] [-e] [-w n]
                      ...`
`winafl-cmin.py: error: one of the arguments -target_method -target_offset is required`

Running WinAFL with the -target_offset is working fine so I can't really tell what I'm missing here. Any help would be appreciated!
Thanks,
doria90

**Comment by 0vercl0k** [comment]
Hey @doria90,

Could you try without the last '\' in your -D argument? My guess is that
you're escaping the final double quote which messes up the command line
parsing.
Let me know!

Cheers

2017-07-30 1:16 GMT-07:00 doria90 <notifications@github.com>:

**Comment by doria90** [comment]
Yep. It works! silly me.. Thanks!!

**Comment by 0vercl0k** [comment]
Awesome! Feel free to close the issue then :-).

Cheers

2017-08-03 1:31 GMT-07:00 doria90 <notifications@github.com>:
