### ISSUE TITLE
why need target_offset ?

### ISSUE THREAD

**Issue by fr0zenrain** [ivanfratric/winafl#7]
i think it's  difficult to choose a offset .it seems afl does not need offset, why winalf  not use static instrumentation with compiler?

**Comment by ivanfratric** [comment]
The whole idea of WinAFL is that it can be used on binaries without having access to the source code. While it is technically possible to accomplish this without specifying target_offset, doing that would be slow because the target process would need to be restarted for each fuzzing iteration.
