### ISSUE TITLE
winalf hang up just when i star fuzz

### ISSUE THREAD

**Issue by goabout2** [ivanfratric/winafl#73]
hi when i use the winalf as the expample say，like blow，it just hang up and there is nothing going no，how can i fix it 
C:\tool\winafl\winafl-master\bin64>afl-fuzz.exe -i in -o out -D C:\tool\winafl\DynamoRIO-Windows-6.2.0-2\bin64 -t 20000 -- -coverage_module gdiplus.dll -coverage_module WindowsCodecs.dll -fuzz_iterations 5000 -target_module test_gdiplus.exe -target_method main -nargs 2 -- testgdiplus.exe @@
WinAFL 1.11 by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
..........

**Comment by uskovboris** [comment]
Hello @goabout2 !
Could you explain to me what the problem was connected with? I've encountered with the same problem and unable to understand the root cause of the hung...
