### ISSUE TITLE
winafl crashes when there's a testcase with size 0 

### ISSUE THREAD

**Issue by ea** [ivanfratric/winafl#75]
Hi, 

i just quickly debugged an issue I had. Through some input corpus manipulation, few of my input files ended up being truncated to 0. 

Original AFL skips over them as there's an explicit check at afl-fuzz.c+1461 : 
`if (!S_ISREG(st.st_mode) || !st.st_size || strstr(fn, "/README.txt"))` where WinAFL
(since lstat isn't available) does it a bit differently at afl-fuzz.c+1437: 
`    if (_access(fn, 0) || (st_size < 0)) `

Not adding a testcase if it's zero and simply skipping it seems to be a valid option.
Wanted to add a pull request , but ... 

Anyway, without the fix, WinAFL will happily run for some time, until it tries to fuzz the zero-length testcase at which point it will crash with devide-by-zero. 
It's a minor issue that showed up through a mistake of my own, but isn't readily apparent when you start fuzzing... 

Cheers!

**Comment by ivanfratric** [comment]
That's a good point, I'll include it in the next release. A PR would also be appreciated :-)

**Comment by ivanfratric** [comment]
This has been fixed by https://github.com/ivanfratric/winafl/pull/94
