### ISSUE TITLE
Is this a mistake in writing?

### ISSUE THREAD

**Issue by chaojianhu** [ivanfratric/winafl#79]
static void event_thread_init(void *drcontext)
{
  void **thread_data;

  thread_data = (void **)dr_thread_alloc(drcontext, 2 * sizeof(void *));
  thread_data[0] = 0;
  if(options.thread_coverage) {
    thread_data[1] = winafl_data.fake_afl_area;
  } else {
    thread_data[0] = 0;                     //Is this a mistake in writing? thread_data[0] or thread_data[1]
  }
  drmgr_set_tls_field(drcontext, winafl_tls_field, thread_data);
}

**Comment by ivanfratric** [comment]
Yes, this is a mistake, but fortunately it doesn't have any negative effects on WinAFL execution since thread_data[1] (pointer to thread-specific afl area) isn't used if options.thread_coverage is false.
Thanks for pointing it out though, I can change it in the next update.

**Comment by ivanfratric** [comment]
This should be fixed now.
