### ISSUE TITLE
Crashes are not caught by winafl

### ISSUE THREAD

**Issue by yoava333** [ivanfratric/winafl#82]
I'm using winafl to fuzz an xml library, every couple of minutes windbg pops up.
Sometimes WinDbg is stuck and I'm forced to kill it.
WinDbg catches crashes that are supposed to be caught by winafl, see below:

```

Microsoft (R) Windows Debugger Version 10.0.14321.1024 X86
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00100000 00107000   c:\work\fuzzing\libxml_test\Release\libxml_test.exe
ModLoad: 76f50000 770d9000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 75f20000 75ff0000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 76650000 7682b000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 75d80000 75e9e000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 63b00000 63b14000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 675c0000 67613000   c:\work\fuzzing\libxml_test\Release\MdXml.dll
ModLoad: 75b80000 75bc5000   C:\WINDOWS\System32\SHLWAPI.dll
ModLoad: 033d0000 0348d000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 76cf0000 76f41000   C:\WINDOWS\System32\combase.dll
ModLoad: 73c80000 73d3f000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 73970000 73990000   C:\WINDOWS\System32\SspiCli.dll
ModLoad: 73960000 7396a000   C:\WINDOWS\System32\CRYPTBASE.dll
ModLoad: 747d0000 74827000   C:\WINDOWS\System32\bcryptPrimitives.dll
ModLoad: 75d20000 75d63000   C:\WINDOWS\System32\sechost.dll
ModLoad: 74170000 74192000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 74670000 747d0000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 75ea0000 75f1c000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 76930000 76aad000   C:\WINDOWS\System32\USER32.dll
ModLoad: 76850000 76867000   C:\WINDOWS\System32\win32u.dll
ModLoad: 73ae0000 73b05000   C:\WINDOWS\System32\IMM32.DLL
(2538.3ee4): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
eax=00000001 ebx=009ead88 ecx=00000007 edx=000001de esi=00000003 edi=00101937
eip=19886857 esp=009eac70 ebp=009eac80 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000202
19886857 cd29            int     29h
0:000> kb
 # ChildEBP RetAddr  Args to Child              
WARNING: Frame IP not in any known module. Following frames may be wrong.
00 009eac80 75e2010b 8783d773 00101937 00000000 0x19886857
*** WARNING: Unable to verify checksum for c:\work\fuzzing\libxml_test\Release\libxml_test.exe
01 009eacb4 00101977 009ead58 767df230 009ead88 ucrtbase!terminate+0x3b
02 009eacbc 767df230 009ead88 ab465cc1 00000000 libxml_test!__scrt_unhandled_exception_filter+0x40 [f:\dd\vctools\crt\vcstartup\src\utility\utility_desktop.cpp @ 75]
03 009ead58 76fef90a 009ead88 76fc16f2 009efce8 KERNELBASE!UnhandledExceptionFilter+0x1a0
04 009efcf8 76fb2ab9 ffffffff 76fd3d49 00000000 ntdll!__RtlUserThreadStart+0x3ce50
05 009efd08 00000000 00101325 00bac000 00000000 ntdll!_RtlUserThreadStart+0x1b
```

I'm using DynamoRio 6.20 & lastest WinAfl.

**Comment by ivanfratric** [comment]
The issue here is that certain exception types have been made in a way that you can't catch it from user-mode without debugging, which means what DynamoRIO / WinAFL won't be able to see them. You can see the exceptions WinAFL currently treats as crashes in https://github.com/ivanfratric/winafl/blob/master/winafl.c#L181

A workaround is to unregister WinDbg as JIT debugger, which is going to prevent it from automatically popping up and afl-fuzz is going to be able to kill the target process. In this case, WinAFL is going to treat exceptions of these types as hangs (so be sure to check out your hangs output folder in addition to crashes).

@0vercl0k started working on another solution to this problem a while ago and you can see his patch in https://github.com/0vercl0k/winafl/commit/c9b6bc7c056643cfc8fd525c8f0ef920023f82fd. Note that it will only work on Windows 8 and up.

**Comment by yoava333** [comment]
@ivanfratric What 's preventing us from introducing this @0vercl0k work to winafl? I think it would benefit many users

**Comment by ivanfratric** [comment]
Hmm good question, I guess it was never submitted (not sure if Axel wanted to do some more work on it).

@0vercl0k want to submit it? :-)

**Comment by 0vercl0k** [comment]
Go for it if you're on a hurry man :). Especially if you have repros of
this issue, it'd be better for you to validate your fix against those etc.

Let me know if you guys want me to take a look to the PRs!

Cheers

2018-03-20 7:44 GMT-07:00 yoava333 <notifications@github.com>:

**Comment by yoava333** [comment]
@0vercl0k I'm not in a hurry and I don't have any new patches, I used your patches and they worked perfectly. I would love them to be in the main tree, so submit a patch when you have time :-)
