### ISSUE TITLE
Potential out-of-bounds read in load_extras()

### ISSUE THREAD

**Issue by LiptonB** [ivanfratric/winafl#83]
The load_extras function contains this code:
`if(in_dir[strlen(dir)-1] == '\\') {`
This appears to be indexing one string (`in_dir`) with the length of a different string (`dir`, which is set from `extras_dir`) and could lead to an out-of-bounds read.

**Comment by ivanfratric** [comment]
Ah, you are right, that should be `dir`. It's fixed in the source now. Thank you for reporting!

**Comment by yoava333** [comment]
I think this issue was resolved in https://github.com/ivanfratric/winafl/commit/61ee185464e8c5f963f19b0d9023158a8b2f5cac, right?

**Comment by LiptonB** [comment]
Indeed, thank you!
