### ISSUE TITLE
Afl prints zero fuzzer_pid

### ISSUE THREAD

**Issue by nevilad** [ivanfratric/winafl#89]
The code in write_stats_file prints zero fuzzer_pid:
  fprintf(f, "start_time        : %llu\n"
             "last_update       : %llu\n"
             "fuzzer_pid        : %u\n"
...
             start_time / 1000, get_cur_time() / 1000, 0,

**Comment by ivanfratric** [comment]
Ah yes, this was carried over from the linux AFL, but zeroed out for simplicity. I guess it could be GetCurrentProcessId. What is the purpose of having fuzzer_pid in the stats file?

**Comment by nevilad** [comment]
I don't use the fuzzer_pid. Would just delete it's output.

**Comment by ivanfratric** [comment]
Fixed in 1.13
