### ISSUE TITLE
drrun is not reading fuzz_iterations 

### ISSUE THREAD

**Issue by romi007r** [ivanfratric/winafl#9]
c:\work\winafl\DynamoRIO-Windows-6.1.1-3\bin64\drrun.exe -c winafl.dll -debug -target_module notepad.exe -target_offset 0x3a14 -fuzz_iterations 5 -nargs 4 -- C:\Windows\system32\notepad.exe test.txt 

runs only one time instead of 5 times 

Module loaded, dynamorio.dll
Module loaded, KERNEL32.dll
Module loaded, USER32.dll
Module loaded, ntdll.dll
Module loaded, winafl.dll
Module loaded, drx.dll
Module loaded, drreg.dll
Module loaded, drmgr.dll
Module loaded, drwrap.dll
Module loaded, notepad.exe
Module loaded, WINSPOOL.DRV
Module loaded, COMCTL32.dll
Module loaded, VERSION.dll
Module loaded, KERNELBASE.dll
Module loaded, ADVAPI32.dll
Module loaded, GDI32.dll
Module loaded, SHLWAPI.dll
Module loaded, USP10.dll
Module loaded, MSCTF.dll
Module loaded, SHELL32.dll
Module loaded, RPCRT4.dll
Module loaded, IMM32.dll
Module loaded, SECHOST.dll
Module loaded, msvcrt.dll
Module loaded, COMDLG32.dll
Module loaded, ole32.dll
Module loaded, LPK.dll
Module loaded, OLEAUT32.dll
Module loaded, VERIFIER.dll
Module loaded, CRYPTBASE.dll
Module loaded, UxTheme.dll
Module loaded, dwmapi.dll
In OpenFileW, reading C:\Windows\Fonts\staticcache.dat
In OpenFileW, reading C:\Users\310222344\Downloads\winafl-master\build64\Debug\templates\fuzz2222222-moe69skripnpti.html

after 1st iteration it does not close automatically 

please suggest

**Comment by ivanfratric** [comment]
It is not supposed to close automatically, that's not how WinAFL works. You need to select a target_offset of a function that will return when processing of your input file is done. See another discussion on this in https://github.com/ivanfratric/winafl/issues/6

**Comment by romi007r** [comment]
i am sure offset is correct because adding @@  after the command line with a space iterate it exactly 5 times but manual intervention is required. 

i am stuck here after all test giving up error

**Comment by romi007r** [comment]
after the manual intervention i am able to get the iterations but again running AFL results in hangs 


1 processes nudged
[!] WARNING: Test case results in a hang (skipping)
[*] Attempting dry run with 'id_000002'...



this is the command line i am using 


afl-fuzz.exe -i in -o new -D c:\winafl-master\dyno\bin64 -t 1000+ --  -coverage_module notepad.exe -target_offset 0x3a14  -target_module  notepad.exe -fuzz_iterations 5000 -nargs 4 -- C:\Windows\system32\notepad.exe

**Comment by ivanfratric** [comment]
Please read the other thread I linked. I assume you are trying to fuzz the WinMain function of notepad.exe. That function won't return without user interaction and WinAFL won't handle that user interaction for you.

**Comment by romi007r** [comment]
@ivanfratric thanks for the help now i have a fair understanding of the issue

**Comment by romi007r** [comment]
thanks @ivanfratric i was able to fuzz programs like internet explorer 64 bit but do you have any recommendation for finding the target function for any generic program

**Comment by ifratric** [comment]
That's a difficult question and I don't think there really is a generic way, it will usually take some reversing of the target to figure out what a good target function might be. Some approaches that might work:
 - If you know where some of the functionality (e.g. file parsing) that you want to fuzz is implemented, you can set a breakpoint somewhere into that and when you hit that breakpoint list a call stack. Your target function should be something on that call stack.
 - Another approach might be to set a breakpoint on file opening functions (e.g. CreateFileA/CreateFileW), look where your input file is opened and do the callstack from there.

**Comment by romi007r** [comment]
hi @ifratric i was successfully able to fuzz many programs any suggestions on how to create valid testcases from the raw fuzzer output in windows

**Comment by ivanfratric** [comment]
I'm not sure if that's what you mean but all samples with new coverage as well as all samples that caused a crash are stored in the WinAFL output directory (same as AFL).

**Comment by romi007r** [comment]
to be precise how can we  produce straightforward reproduction cases from the sample in crash folder , such as an HTML for a browser or as specific file format
