### ISSUE TITLE
drrun.exe shows the output only once, and test cases times out

### ISSUE THREAD

**Issue by 4br3mm0rd** [ivanfratric/winafl#90]
Hi,

I am currently trying to run winafl on a sample 32bit program (that I coded for the example) using DynamoRIO.

I encountered 2 problems which are probably linked. The first problem occurs when I run the DynamoRIO drrun.exe with the following command line:
`..\..\DynamoRIO-Windows-6.2.0-2\bin32\drrun.exe -c winafl.dll -debug -target_module fuzz\example.exe -target_offset 0x10790 -fuzz_iterations 10 -nargs 2 -- fuzz\example.exe input\in01.txt`

where 0x10790 is the address of the main function in my binary.

The output should be 10 times the output of my program according to the documentation. However it appears only once.
When I then try to run afl-fuzz using the following command, it says that my test cases time out (although it takes less than the timeout time I set to skip...):
`afl-fuzz.exe -i input -o output -D C:\Users\myUser\Desktop\DynamoRIO-Windows-6.2.0-2\bin32 -t 1000+ -- -coverage_module fuzz\example.exe -target_offset 0x10790 -target_module fuzz\example.exe -fuzz_iterations 5000 -nargs 2 -- fuzz\example.exe @@`

Do you have any idea of what is happening here?

Thank you!

**Comment by ivanfratric** [comment]
What does your debug log say?

**Comment by ivanfratric** [comment]
Also,
`-target_module fuzz\example.exe`
should be
`-target_module example.exe`
(target_module takes just the module name, not the path)

**Comment by 4br3mm0rd** [comment]
Thanks for the answer, it was exactly this :)
